### ISSUE TITLE
Python based source code

### ISSUE THREAD

**Issue by srikanthBezawada** [ItzikMalkiel/DeepNanoDesign#4]
Is there a PyTorch (or) any other Python based source code available for the same ? Thanks!

**Comment by ItzikMalkiel** [comment]
I have some version of this work, based on tensorflow, but (1) it's not the original code that I used in order to get the results reported in the paper, (2) the implementation aims to solve this problem with a different technique, that can be interesting for future research and (3) I didn't test the code, but it does give some interesting preliminary results. 

If you find it interesting, please shoot me an email at itzik.malkiel@gmail.com

**Comment by srikanthBezawada** [comment]
Thanks for your response! 
I sent you the email..

**Comment by Yi-Jeremy** [comment]
Hello @srikanthBezawada !Have you received the Python code of the paper? I would be very grateful if you have received the python code and send it to me via hkjoe8191@gmail.com .

**Comment by srikanthBezawada** [comment]
@HKjoe  nope. have not received.
